// <auto-generated />
using System;
using Adenawell_ValentinAP1_P1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adenawell_ValentinAP1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260221171908_AgregandoTiposData")]
    partial class AgregandoTiposData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Adenawell_ValentinAP1_P1.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Rojo",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Verde",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Amarillo",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntrada"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradasHuacales");
                });
#pragma warning restore 612, 618
        }
    }
}
